# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 세상을 바꾸는 개발자, minha
tagline: 'since 2023'
description: 계속 성장하는 개발자 손민하 블로그 입니다.
url: http://hyde.getpoole.com
baseurl: /

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/skylotus0206/skylotus0206.github.io.git
